
## Что такое исключения в Python

Исключения в Python — это события, которые возникают во время выполнения программы и сигнализируют о том, что что-то пошло не так, как ожидалось. Эти события случаются по разным причинам:

- ошибка в коде,
- неправильные входные данные,
- нехватка памяти,
- и так далее.

Исключение — это не ошибка. Но исключение может быть результатом ошибки.


**Ошибка** обычно относится к более широкой категории проблем. Она указывает на некорректное состояние программы, которое может привести к её аварийному завершению.

**Исключение** — это специальный механизм, который позволяет обрабатывать ошибки и управлять ими. Так работа кода становится более предсказуемой и контролируемой.


Вот некоторые исключения, с которыми вы можете столкнуться:

- **ZeroDivisionError** — деление на ноль.
- **ImportError** — проблемы с импортом модулей и пакетов.
- **IndexError** — индекс последовательности находится вне допустимого диапазона.
- **KeyError** — ключ словаря не найден в наборе существующих ключей.
- **SyntaxError** — синтаксическая ошибка.
- **TypeError** — операция применяется к объекту несоответствующего типа.
- **ValueError** — функция получила аргумент правильного типа, но с недопустимым значением.

**!!!**
Программисты могут не только использовать стандартные исключения, но и создавать собственные. Для этого нужно создать новый класс, унаследованный от встроенного класса `Exception`.


## Как описать собственное исключение

Чтобы описать собственное исключение, нужно:

1. Создать новый класс, который наследуется от встроенного класса `Exception` или его подклассов. Подклассы — это конкретные исключения, например `SyntaxError`, `TypeError`, `IndexError`. Имя класса придумывает разработчик, но оно должно заканчиваться словом `Error`.
2. Переопределить метод `__str__()`. В нём можно понятным языком описать, что учитывает конкретное исключение.


## «Укрощение» исключений в Python

Обычно программисты стараются заранее предусмотреть возникновение нештатных ситуаций при работе кода. Например, прежде чем делить значение на какое-то число, можно предварительно проверить, что это число не равно `0`.


Но есть и другой способ. Чтобы программа не останавливалась при возникновении исключений, код, который потенциально может вызвать исключение, заключают в специальную конструкцию. Обработка исключений в этом случае происходит с использованием нескольких ключевых слов: `try`, `except`, `else` и `finally`.

Вот как они работают:

- Блок `try` («попробовать») содержит операции, которые могут вызвать исключение. Если при выполнении кода внутри этого блока возникает исключение, программа не останавливается, а переходит к блоку с инструкциями `except`.
    
    
    ```
      try:
          # Блок кода, который может вызвать исключение.
       
    ```
    
- Блок `except` («исключая») обрабатывает исключение, возникшее в блоке `try`.
    
    
    ```
      except SomeException as e:
          # Обработка исключения.
       
    ```
    
    `SomeException` — это конкретный тип исключения, который вы хотите обработать. Можно указать несколько блоков `except` для обработки разных типов исключений.
    
    
    ```
      except TypeError:
          # Обработка TypeError.
      except ValueError:
          # Обработка ValueError.
      except Exception as e:
          # Обработка остальных исключений.
          # Доступ к объекту исключения в коде программы
          # можно получить через переменную 'e'.
       
    ```
    
- Блок `else` («иначе») выполняется, если в блоке `try` не возникло исключений. Это хорошее место для кода, который должен выполняться **только в том случае**, когда операции в `try` прошли успешно.
    
    
    ```
      else:
          # Блок кода, который выполняется, если исключение не возникло.
       
    ```
    
- Блок кода `finally` («в любом случае») выполняется независимо от того, произошло исключение или нет.
    
    
    ```
      finally:
          # Блок кода, который выполняется всегда.
       
    ```
    

Пример «укрощения» исключения:


```
try:
    # Блок кода, который может вызвать исключение.
    result = 10 / 0
except ZeroDivisionError as e:
    # Обработка исключения при делении на ноль.
    print(f'Ошибка: {e}')
else:
    # Блок кода, который выполняется, если исключение не возникло.
    print('Операция выполнена успешно.')
finally:
    # Блок кода, который выполняется всегда.
    print('Программа завершила свою работу.') 
```

Если произойдёт деление на ноль, сначала выполнится код в блоке `except`, а потом — в блоке `finally`. Если исключение не произойдёт, выполнится блок `else` и затем блок `finally`.

Блоки `else` и `finally` — необязательные. Если их не будет, то после того, как произойдёт ситуация, которая может вызывать исключение, и исключение будет обработано, управление программой перейдёт к основному коду.


Если возникнет любая ситуация, которая не описана в коде, можно сделать так, чтобы программа печатала сообщение `Возникла ошибка: <название исключения>`.

Чтобы реализовать такое поведение программы, нужно добавить блок `except Exception`. 

Это обработка базового класса исключений, которую обычно добавляют после обработки конкретных, ожидаемых исключений. 

Если при работе блока кода возникнет исключение, обработка которого не описана явным образом, оно будет перехвачено именно тут.


