[[Python]]
[[Фреймворк Django. Работа с проектами]]
[[Питон Практикум]]

Запуская тесты для домашних заданий вы могли столкнуться с ситуацией, когда часть тестов прошла успешно, а часть провалилась. И после исправлений, при следующем запуске pytest, приходится ждать, пока выполнятся все тесты, включая те, что и в первый раз были пройдены успешно.

Если тестов немного — проблем нет, но когда их сотни — ожидание может стать утомительным. Разработчики pytest предусмотрели эту проблему: после выполнения тестов в директории _.pytest_cache/_ сохраняется список провалившихся тестов, и при следующем тестировании можно запустить лишь те тесты, которые в прошлый раз вернули ошибку.

- при запуске тестов с ключом `--lf` (он же `--last-failed`) будут выполнены только те тесты, которые провалились в прошлый раз;
- при запуске тестов с ключом `--ff` (он же `--failed-first`) сначала будут выполнены провалившиеся тесты, а после них — все остальные. Полезный способ для ситуаций, когда исправление одной ошибки могло повлечь возникновение другой;

В кеше сохраняется полный список обнаруженных тестов, и за счёт этого pytest может «увидеть» новые тесты — те, что появились с момента последнего тестирования. Можно запустить тесты так, что сначала выполнятся новые — те, о которых нет записей в кеше, а после них — все остальные. Для этого надо выполнить команду `pytest` с ключом `--nf` (он же `--new-first`). При этом «старые» тесты будут выполняться в порядке «сначала новые, потом старые», в зависимости от даты модификации файлов с тестами.

Проверьте, что содержимое вашего файла _test_example.py_ не изменилось: сейчас вам предстоит погонять тесты с разными ключами и разобраться с их применением.

```
# test_example.py
def one_more(x):
    return x + 1


def get_sort_list(str):
    new_list = sorted(str.split(', '))
    return new_list


def test_correct():
    assert one_more(4) == 5


def test_fail():
    assert one_more(3) == 5


def test_sort():
    """Тестируем функцию get_sort_list()."""
    result = get_sort_list('Яша, Саша, Маша, Даша')
    assert result == ['Даша', 'Маша', 'Саша', 'Яша'] 
```

Выполните эту команду в той директории, где сохранён ваш файл _test_example.py_

```
pytest test_example.py -qq --lf 
```

Самостоятельно разберитесь, что делает команда и для чего нужны ключи.

Какой результат вы получили при выполнении тестов?

Введите строку из отчёта о тестировании — краткий результат, где точка - это успешно пройденный тест, а F - проваленный. Например: `F.F.F.`

Ваш ответ правильный

F

Верно, по ключу `--lf` был запущен только один тест — тот, который провалился в прошлый раз. И он провалился снова. А ключ `-qq` просто сделал отчёт лаконичнее.

Как вам задача?

Запустите тесты

```
pytest test_example.py -qq --ff 
```

Какой результат вы получили при выполнении тестов?

Введите строку из отчёта о тестировании — краткий результат, где точка - это успешно пройденный тест, а F - проваленный. Например: `F.F.F.`

Ваш ответ правильный

F..

Верно, были запущены все тесты; первым был выполнен тот, который провалился в прошлый раз.

Как вам задача?

## Тестирование в режиме «до первого упавшего теста»

Пожалуй, один из самых полезных ключей в pytest — это `-x` (он же `--exitfirst`): «остановить выполнение тестов при первом же падении». Если хотя бы один тест упал — значит, что-то не в порядке, и надо разбираться с кодом, а не ждать, пока будут пройдены все тесты.

Когда падает множество тестов, то вывод забивается избыточной информацией, анализировать результаты неудобно; а зачастую падение нескольких тестов зависит от одной и той же ошибки, и её исправление «вылечит» все поломанные тесты.

Запустите в терминале команду `pytest --ff -x`: «начать с провалившихся тестов и остановиться при первом же падении теста».

Сначала выполнится тест `test_fail`, он упадёт — и выполнение тестов остановится. Без ключа `-x` выполнились бы все тесты без остановки.

Выполнение тестов можно останавливать не только после первого падения, но и после провала любого другого количества тестов. Количество можно указать в ключе `--maxfail=N`, где `N` — число проваленных тестов. Например, при запуске тестов с ключом `--maxfail=3` выполнение остановится после падения трёх тестов.

## Поэтапное выполнение тестов: stepwise

Режим stepwise (запуск с ключом `--sw` или `--stepwise`) — это пошаговое выполнение тестов, при котором можно «фиксить» проблемы по очереди.

При запуске тестов с ключом `--sw` тесты выполняются до тех пор, пока один из них не упадёт; после падения выполнение тестов останавливается (точно как с ключом `-x`). После этого можно поправить код и снова запустить тесты с ключом `--sw`; выполнение начнётся с упавшего теста и продолжится дальше.

Этот режим чем-то похож на комбинацию ключей `--lf -x`: «запустить все провалившиеся тесты и остановиться на первом упавшем». Но у режима stepwise есть полезная особенность: если не удаётся решить проблему с каким-то падающим тестом — его можно пропустить и перейти к следующему. Делается это при помощи ключа `--stepwise-skip`. Непокорный тест будет пропущен, и больше в этом поэтапном режиме он появляться не будет, выполнение тестов пойдёт дальше.

## Кеш pytest

Все перечисленные варианты запуска реализуются за счёт того, что pytest сохраняет в кеше информацию о выполненных тестах.

При первом запуске тестов pytest создаёт директорию `.pytest_cache`, в которой сохраняет данные о том, какие тесты были запущены и с каким результатом они завершились.

Бывает, что в результате переименования или перемещения тестов возникают конфликты между именами различных файлов и тестов, в таких случаях можно просто удалить директорию с кешем. Pytest сам напомнит об этом при необходимости:

```
import file mismatch:
imported module 'test_dir' has this __file__ attribute:
  <путь>\t1\test_dir.py
which is not the same as the test file we want to collect:
  <путь>\t2\test_dir.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules 
```

После удаления директории с кешем вся информация о предыдущих запусках будет стёрта.

Добавьте в конец файла _test_example.py_ ещё один тест — он заведомо провальный:

```
def test_type():
    """Тестируем тип данных, возвращаемых из get_sort_list()."""
    result = get_sort_list('Яша, Саша, Маша, Даша')
    # Провальный тест:
    # ожидаем число, но вернётся список.
    assert isinstance(result, int)   
```

Запустите тесты такой командой:

```
pytest test_example.py -qq --nf 
```

Какой результат вы получили при выполнении тестов? Имейте в виду, что повторное выполнение команды с ключом `--nf` вернёт другой результат.

Введите строку из отчёта о тестировании — краткий результат, где точка - это успешно пройденный тест, а F - проваленный. Например: `F.F.F.`

Ваш ответ правильный

F.F.

Верно. Были запущены все тесты; первым был выполнен новый тест, а следом — все остальные

